CREATE TABLE faculty (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    foundation_year integer NOT NULL CHECK (foundation_year >= 1900)
);

CREATE TABLE student (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    birth_date date NOT NULL,
    faculty_id integer NOT NULL REFERENCES faculty(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    email text UNIQUE
);

CREATE TABLE course (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    credits integer NOT NULL CHECK (credits BETWEEN 1 AND 10),
    faculty_id integer NOT NULL REFERENCES faculty(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE enrollment (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL REFERENCES student(id) ON UPDATE CASCADE ON DELETE CASCADE,
    course_id  integer NOT NULL REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE,
    enroll_date date NOT NULL DEFAULT CURRENT_DATE
);