CREATE TABLE faculty (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    foundation_year integer NOT NULL CHECK (foundation_year >= 1900)
);

CREATE TABLE student (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    birth_date date NOT NULL,
    faculty_id integer NOT NULL REFERENCES faculty(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    email text UNIQUE
);

CREATE TABLE course (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    credits integer NOT NULL CHECK (credits BETWEEN 1 AND 10),
    faculty_id integer NOT NULL REFERENCES faculty(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE enrollment (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL REFERENCES student(id) ON UPDATE CASCADE ON DELETE CASCADE,
    course_id  integer NOT NULL REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE,
    enroll_date date NOT NULL DEFAULT CURRENT_DATE
);

INSERT INTO faculty (id, name, foundation_year) VALUES
  (1, 'Факультет компьютерных наук', 1957),
  (2, 'Математический факультет', 1930),
  (3, 'Физический факультет', 1912);

INSERT INTO student (id, full_name, birth_date, faculty_id, email) VALUES
  (100, 'Анна Петрова', DATE '2003-03-14', 1, 'anna.petrova@example.edu'),
  (101, 'Иван Сидоров', DATE '2002-11-05', 1, 'ivan.sidorov@example.edu'),
  (102, 'Мария Иванова', DATE '2001-07-22', 2, 'maria.ivanova@example.edu'),
  (103, 'Дмитрий Смирнов', DATE '2002-02-10', 2, 'dmitry.smirnov@example.edu'),
  (104, 'Елена Кузнецова', DATE '2003-09-02', 3, 'elena.kuznetsova@example.edu'),
  (105, 'Олег Орлов', DATE '2001-12-18', 3, 'oleg.orlov@example.edu');

INSERT INTO course (id, name, credits, faculty_id) VALUES
  (200, 'Алгоритмы', 6, 1),
  (201, 'Базы данных', 5, 1),
  (202, 'Математический анализ', 6, 2),
  (203, 'Линейная алгебра', 5, 2),
  (204, 'Квантовая механика', 7, 3);

INSERT INTO enrollment (id, student_id, course_id, enroll_date) VALUES
  (1000, 100, 200, CURRENT_DATE),
  (1001, 100, 201, CURRENT_DATE),
  (1002, 101, 200, CURRENT_DATE),
  (1003, 102, 202, CURRENT_DATE),
  (1004, 103, 203, CURRENT_DATE),
  (1005, 104, 204, CURRENT_DATE),
  (1006, 105, 204, CURRENT_DATE),
  (1007, 102, 200, CURRENT_DATE);

  --1
SELECT s.full_name AS student, f.name AS faculty
FROM student AS s
JOIN faculty AS f ON f.id = s.faculty_id
ORDER BY s.full_name;

--2
SELECT c.name AS course, f.name AS faculty
FROM course AS c
JOIN faculty AS f ON c.faculty_id = f.id
ORDER BY c.name;

--3
SELECT s.full_name AS student, c.name AS course
FROM enrollment AS e
JOIN student AS s ON e.student_id = s.id
JOIN course AS c ON e.course_id = c.id
ORDER BY s.full_name, c.name;

--4
SELECT s.full_name AS student
FROM enrollment AS e
JOIN student AS s ON s.id = e.student_id
GROUP BY s.id, s.full_name
HAVING COUNT(DISTINCT e.course_id) > 1
ORDER BY s.full_name;

--5
SELECT c.name AS course
FROM course AS c
JOIN enrollment AS e ON e.course_id = c.id
GROUP BY c.id, c.name
HAVING COUNT(DISTINCT e.student_id) > 2
ORDER BY c.name;